import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const categoryApi = createApi({
  reducerPath: "categoryApi",
  baseQuery: fetchBaseQuery({ baseUrl: "https://journal2.nordicun.uz" }), // Ensure this environment variable is set
  endpoints: (build) => ({
    getAllCategory: build.query<categoryType[], void>({
      query: () => "/category",
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useGetAllCategoryQuery } = categoryApi;
