import type { Metadata } from "next";
import { Bellota_Text, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/main/Navbar";

const inter = Bellota_Text({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
