import type { Metadata } from "next";
import { Bellota_Text } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/main/Navbar";
import React from "react";
import StoreProvider from "@/lib/provider/StoreProvider";
import Footer from "@/app/components/main/Footer";

const inter = Bellota_Text({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
