import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import React from "react";
import TopNav from "@/app/components/main/top.nav";
import Nav from "@/app/components/main/nav";
import MainFooter from "@/app/components/main/MainFooter";
import Hero from "@/app/components/main/Hero";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { StoreProvider } from "@/app/utils/provider/storeProvider";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={params.locale}>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <StoreProvider>
            <TopNav />
            <Nav />
            <main className="flex-grow">{children}</main>
            <MainFooter />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
