import Head from "next/head";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import React from "react";
import TopNav from "@/app/components/main/top.nav";
import Nav from "@/app/components/main/nav";
import MainFooter from "@/app/components/main/MainFooter";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { StoreProvider } from "@/app/utils/provider/storeProvider";
import { getCurrentLangServer } from "@/app/helpers/getLangForServer";
import { ConfigProvider } from "antd";
import uzLatn from "antd/locale/uz_UZ";
import ruLatn from "antd/locale/ru_RU";
import enLatn from "antd/locale/en_US";
import AccessibilityDrawer from "@/app/components/UI/acessibility";

const getAllResources = async () => {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_URL_BACKEND}/api/education/resources?language=${await getCurrentLangServer()}`,
    {
      cache: "no-cache",
    },
  );
  const json = await response.json();
  return json;
};

const getAllNetworks = async () => {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_URL_BACKEND}/api/core/social-network?page=1&limit=4`,
    {
      cache: "no-cache",
    },
  );
  const json = await response.json();
  return json;
};

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Nordic - University",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { lang: string };
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const messages = await getMessages();
  const networks = await getAllNetworks();
  const resources = await getAllResources();

  return (
    <html lang={params.lang}>
      <Head>
        <meta
          name="google-site-verification"
          content="8FJy9noEZAx-f0QKd8R0mFWvBPxym2l_FD-jw1WgSOk"
        />
      </Head>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <NextIntlClientProvider locale={params.lang} messages={messages}>
          <ConfigProvider
            locale={
              params.lang === "uz"
                ? uzLatn
                : params.lang === "en"
                  ? enLatn
                  : ruLatn
            }
          >
            <StoreProvider>
              <TopNav props={resources} networks={networks.data} />
              <Nav />
              <main className="flex-grow">{children}</main>
              <MainFooter />
            </StoreProvider>
          </ConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
